// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/contact/contact.proto

package contact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     int32                  `protobuf:"varint,1,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,proto3,oneof" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_proto_contact_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *Contact) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Contact) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Contact) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Contact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     int32                  `protobuf:"varint,1,opt,name=address_id,proto3" json:"address_id,omitempty"`
	ContactId     int32                  `protobuf:"varint,2,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	Street        *string                `protobuf:"bytes,3,opt,name=street,proto3,oneof" json:"street,omitempty"`
	City          *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string                `protobuf:"bytes,5,opt,name=state,proto3,oneof" json:"state,omitempty"`
	ZipCode       *string                `protobuf:"bytes,6,opt,name=zip_code,proto3,oneof" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_contact_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *Address) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *Address) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil && x.ZipCode != nil {
		return *x.ZipCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetContactByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	ContactId     int32                  `protobuf:"varint,2,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactByIdRequest) Reset() {
	*x = GetContactByIdRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactByIdRequest) ProtoMessage() {}

func (x *GetContactByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactByIdRequest.ProtoReflect.Descriptor instead.
func (*GetContactByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{2}
}

func (x *GetContactByIdRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetContactByIdRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

type GetContactByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactByIdResponse) Reset() {
	*x = GetContactByIdResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactByIdResponse) ProtoMessage() {}

func (x *GetContactByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactByIdResponse.ProtoReflect.Descriptor instead.
func (*GetContactByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{3}
}

func (x *GetContactByIdResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type GetContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactsRequest) Reset() {
	*x = GetContactsRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactsRequest) ProtoMessage() {}

func (x *GetContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactsRequest.ProtoReflect.Descriptor instead.
func (*GetContactsRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{4}
}

func (x *GetContactsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetContactsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetContactsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetContactsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type GetContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	TotalData     int32                  `protobuf:"varint,2,opt,name=total_data,proto3" json:"total_data,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,proto3" json:"current_page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	TotalPage     int32                  `protobuf:"varint,5,opt,name=total_page,proto3" json:"total_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactsResponse) Reset() {
	*x = GetContactsResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactsResponse) ProtoMessage() {}

func (x *GetContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactsResponse.ProtoReflect.Descriptor instead.
func (*GetContactsResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{5}
}

func (x *GetContactsResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *GetContactsResponse) GetTotalData() int32 {
	if x != nil {
		return x.TotalData
	}
	return 0
}

func (x *GetContactsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetContactsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetContactsResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

type CreateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,proto3,oneof" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactRequest) Reset() {
	*x = CreateContactRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactRequest) ProtoMessage() {}

func (x *CreateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactRequest.ProtoReflect.Descriptor instead.
func (*CreateContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{6}
}

func (x *CreateContactRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateContactRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateContactRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *CreateContactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateContactRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type CreateContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactResponse) Reset() {
	*x = CreateContactResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactResponse) ProtoMessage() {}

func (x *CreateContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactResponse.ProtoReflect.Descriptor instead.
func (*CreateContactResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{7}
}

func (x *CreateContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type UpdateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	ContactId     int32                  `protobuf:"varint,2,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	FirstName     *string                `protobuf:"bytes,3,opt,name=first_name,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,proto3,oneof" json:"last_name,omitempty"`
	Email         *string                `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContactRequest) Reset() {
	*x = UpdateContactRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactRequest) ProtoMessage() {}

func (x *UpdateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactRequest.ProtoReflect.Descriptor instead.
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateContactRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateContactRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *UpdateContactRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateContactRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateContactRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateContactRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type UpdateContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContactResponse) Reset() {
	*x = UpdateContactResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactResponse) ProtoMessage() {}

func (x *UpdateContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactResponse.ProtoReflect.Descriptor instead.
func (*UpdateContactResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type DeleteContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	ContactId     int32                  `protobuf:"varint,2,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactRequest) Reset() {
	*x = DeleteContactRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactRequest) ProtoMessage() {}

func (x *DeleteContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteContactRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteContactRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

type DeleteContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactResponse) Reset() {
	*x = DeleteContactResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactResponse) ProtoMessage() {}

func (x *DeleteContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactResponse.ProtoReflect.Descriptor instead.
func (*DeleteContactResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type GetAddressByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     int32                  `protobuf:"varint,1,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	AddressId     int32                  `protobuf:"varint,2,opt,name=address_id,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressByIdRequest) Reset() {
	*x = GetAddressByIdRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByIdRequest) ProtoMessage() {}

func (x *GetAddressByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAddressByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{12}
}

func (x *GetAddressByIdRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *GetAddressByIdRequest) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type GetAddressByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressByIdResponse) Reset() {
	*x = GetAddressByIdResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByIdResponse) ProtoMessage() {}

func (x *GetAddressByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAddressByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{13}
}

func (x *GetAddressByIdResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     int32                  `protobuf:"varint,1,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesRequest) Reset() {
	*x = GetAddressesRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesRequest) ProtoMessage() {}

func (x *GetAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetAddressesRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{14}
}

func (x *GetAddressesRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *GetAddressesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAddressesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAddressesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

type GetAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	TotalData     int32                  `protobuf:"varint,2,opt,name=total_data,proto3" json:"total_data,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,proto3" json:"current_page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	TotalPage     int32                  `protobuf:"varint,5,opt,name=total_page,proto3" json:"total_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressesResponse) Reset() {
	*x = GetAddressesResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressesResponse) ProtoMessage() {}

func (x *GetAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetAddressesResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{15}
}

func (x *GetAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetAddressesResponse) GetTotalData() int32 {
	if x != nil {
		return x.TotalData
	}
	return 0
}

func (x *GetAddressesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetAddressesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAddressesResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     int32                  `protobuf:"varint,1,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode       string                 `protobuf:"bytes,5,opt,name=zip_code,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAddressRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateAddressRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *CreateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CreateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressResponse) Reset() {
	*x = CreateAddressResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressResponse) ProtoMessage() {}

func (x *CreateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{17}
}

func (x *CreateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     int32                  `protobuf:"varint,1,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	AddressId     int32                  `protobuf:"varint,2,opt,name=address_id,proto3" json:"address_id,omitempty"`
	Street        *string                `protobuf:"bytes,3,opt,name=street,proto3,oneof" json:"street,omitempty"`
	City          *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string                `protobuf:"bytes,5,opt,name=state,proto3,oneof" json:"state,omitempty"`
	ZipCode       *string                `protobuf:"bytes,6,opt,name=zip_code,proto3,oneof" json:"zip_code,omitempty"`
	Country       *string                `protobuf:"bytes,7,opt,name=country,proto3,oneof" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateAddressRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *UpdateAddressRequest) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *UpdateAddressRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *UpdateAddressRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateAddressRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *UpdateAddressRequest) GetZipCode() string {
	if x != nil && x.ZipCode != nil {
		return *x.ZipCode
	}
	return ""
}

func (x *UpdateAddressRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

type UpdateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressResponse) Reset() {
	*x = UpdateAddressResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressResponse) ProtoMessage() {}

func (x *UpdateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     int32                  `protobuf:"varint,1,opt,name=contact_id,proto3" json:"contact_id,omitempty"`
	AddressId     int32                  `protobuf:"varint,2,opt,name=address_id,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_proto_contact_contact_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteAddressRequest) GetContactId() int32 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *DeleteAddressRequest) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_proto_contact_contact_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contact_contact_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_contact_contact_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_proto_contact_contact_proto protoreflect.FileDescriptor

const file_proto_contact_contact_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/contact/contact.proto\x12\acontact\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x02\n" +
	"\aContact\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\x05R\n" +
	"contact_id\x12\x18\n" +
	"\auser_id\x18\x02 \x01(\x05R\auser_id\x12\x1e\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\n" +
	"first_name\x12!\n" +
	"\tlast_name\x18\x04 \x01(\tH\x00R\tlast_name\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x01R\x05phone\x88\x01\x01\x12:\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_atB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_phone\"\xbc\x02\n" +
	"\aAddress\x12\x1e\n" +
	"\n" +
	"address_id\x18\x01 \x01(\x05R\n" +
	"address_id\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x05R\n" +
	"contact_id\x12\x1b\n" +
	"\x06street\x18\x03 \x01(\tH\x00R\x06street\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x01R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x05 \x01(\tH\x02R\x05state\x88\x01\x01\x12\x1f\n" +
	"\bzip_code\x18\x06 \x01(\tH\x03R\bzip_code\x88\x01\x01\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12:\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_atB\t\n" +
	"\a_streetB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\v\n" +
	"\t_zip_code\"Q\n" +
	"\x15GetContactByIdRequest\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x05R\n" +
	"contact_id\"D\n" +
	"\x16GetContactByIdResponse\x12*\n" +
	"\acontact\x18\x01 \x01(\v2\x10.contact.ContactR\acontact\"\x80\x01\n" +
	"\x12GetContactsRequest\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x00R\x06search\x88\x01\x01B\t\n" +
	"\a_search\"\xc5\x01\n" +
	"\x13GetContactsResponse\x12,\n" +
	"\bcontacts\x18\x01 \x03(\v2\x10.contact.ContactR\bcontacts\x12\x1e\n" +
	"\n" +
	"total_data\x18\x02 \x01(\x05R\n" +
	"total_data\x12\"\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\fcurrent_page\x12\x1c\n" +
	"\tpage_size\x18\x04 \x01(\x05R\tpage_size\x12\x1e\n" +
	"\n" +
	"total_page\x18\x05 \x01(\x05R\n" +
	"total_page\"\xbc\x01\n" +
	"\x14CreateContactRequest\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\x12\x1e\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\n" +
	"first_name\x12!\n" +
	"\tlast_name\x18\x03 \x01(\tH\x00R\tlast_name\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x01R\x05phone\x88\x01\x01B\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_phone\"C\n" +
	"\x15CreateContactResponse\x12*\n" +
	"\acontact\x18\x01 \x01(\v2\x10.contact.ContactR\acontact\"\xff\x01\n" +
	"\x14UpdateContactRequest\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x05R\n" +
	"contact_id\x12#\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tH\x00R\n" +
	"first_name\x88\x01\x01\x12!\n" +
	"\tlast_name\x18\x04 \x01(\tH\x01R\tlast_name\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x03R\x05phone\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phone\"C\n" +
	"\x15UpdateContactResponse\x12*\n" +
	"\acontact\x18\x01 \x01(\v2\x10.contact.ContactR\acontact\"P\n" +
	"\x14DeleteContactRequest\x12\x18\n" +
	"\auser_id\x18\x01 \x01(\x05R\auser_id\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x05R\n" +
	"contact_id\"C\n" +
	"\x15DeleteContactResponse\x12*\n" +
	"\acontact\x18\x01 \x01(\v2\x10.contact.ContactR\acontact\"W\n" +
	"\x15GetAddressByIdRequest\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\x05R\n" +
	"contact_id\x12\x1e\n" +
	"\n" +
	"address_id\x18\x02 \x01(\x05R\n" +
	"address_id\"D\n" +
	"\x16GetAddressByIdResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.contact.AddressR\aaddress\"\x87\x01\n" +
	"\x13GetAddressesRequest\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\x05R\n" +
	"contact_id\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x00R\x06search\x88\x01\x01B\t\n" +
	"\a_search\"\xc8\x01\n" +
	"\x14GetAddressesResponse\x12.\n" +
	"\taddresses\x18\x01 \x03(\v2\x10.contact.AddressR\taddresses\x12\x1e\n" +
	"\n" +
	"total_data\x18\x02 \x01(\x05R\n" +
	"total_data\x12\"\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\fcurrent_page\x12\x1c\n" +
	"\tpage_size\x18\x04 \x01(\x05R\tpage_size\x12\x1e\n" +
	"\n" +
	"total_page\x18\x05 \x01(\x05R\n" +
	"total_page\"\xae\x01\n" +
	"\x14CreateAddressRequest\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\x05R\n" +
	"contact_id\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1a\n" +
	"\bzip_code\x18\x05 \x01(\tR\bzip_code\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\"C\n" +
	"\x15CreateAddressResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.contact.AddressR\aaddress\"\x9e\x02\n" +
	"\x14UpdateAddressRequest\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\x05R\n" +
	"contact_id\x12\x1e\n" +
	"\n" +
	"address_id\x18\x02 \x01(\x05R\n" +
	"address_id\x12\x1b\n" +
	"\x06street\x18\x03 \x01(\tH\x00R\x06street\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x01R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x05 \x01(\tH\x02R\x05state\x88\x01\x01\x12\x1f\n" +
	"\bzip_code\x18\x06 \x01(\tH\x03R\bzip_code\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\a \x01(\tH\x04R\acountry\x88\x01\x01B\t\n" +
	"\a_streetB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\v\n" +
	"\t_zip_codeB\n" +
	"\n" +
	"\b_country\"C\n" +
	"\x15UpdateAddressResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.contact.AddressR\aaddress\"V\n" +
	"\x14DeleteAddressRequest\x12\x1e\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\x05R\n" +
	"contact_id\x12\x1e\n" +
	"\n" +
	"address_id\x18\x02 \x01(\x05R\n" +
	"address_id\"C\n" +
	"\x15DeleteAddressResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.contact.AddressR\aaddress2\xad\x06\n" +
	"\x0eContactService\x12Q\n" +
	"\x0eGetContactById\x12\x1e.contact.GetContactByIdRequest\x1a\x1f.contact.GetContactByIdResponse\x12H\n" +
	"\vGetContacts\x12\x1b.contact.GetContactsRequest\x1a\x1c.contact.GetContactsResponse\x12N\n" +
	"\rCreateContact\x12\x1d.contact.CreateContactRequest\x1a\x1e.contact.CreateContactResponse\x12N\n" +
	"\rUpdateContact\x12\x1d.contact.UpdateContactRequest\x1a\x1e.contact.UpdateContactResponse\x12N\n" +
	"\rDeleteContact\x12\x1d.contact.DeleteContactRequest\x1a\x1e.contact.DeleteContactResponse\x12Q\n" +
	"\x0eGetAddressById\x12\x1e.contact.GetAddressByIdRequest\x1a\x1f.contact.GetAddressByIdResponse\x12K\n" +
	"\fGetAddresses\x12\x1c.contact.GetAddressesRequest\x1a\x1d.contact.GetAddressesResponse\x12N\n" +
	"\rCreateAddress\x12\x1d.contact.CreateAddressRequest\x1a\x1e.contact.CreateAddressResponse\x12N\n" +
	"\rUpdateAddress\x12\x1d.contact.UpdateAddressRequest\x1a\x1e.contact.UpdateAddressResponse\x12N\n" +
	"\rDeleteAddress\x12\x1d.contact.DeleteAddressRequest\x1a\x1e.contact.DeleteAddressResponseBFZDgithub.com/DioSaputra28/contact-management-proto/protogen/go/contactb\x06proto3"

var (
	file_proto_contact_contact_proto_rawDescOnce sync.Once
	file_proto_contact_contact_proto_rawDescData []byte
)

func file_proto_contact_contact_proto_rawDescGZIP() []byte {
	file_proto_contact_contact_proto_rawDescOnce.Do(func() {
		file_proto_contact_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_contact_contact_proto_rawDesc), len(file_proto_contact_contact_proto_rawDesc)))
	})
	return file_proto_contact_contact_proto_rawDescData
}

var file_proto_contact_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_contact_contact_proto_goTypes = []any{
	(*Contact)(nil),                // 0: contact.Contact
	(*Address)(nil),                // 1: contact.Address
	(*GetContactByIdRequest)(nil),  // 2: contact.GetContactByIdRequest
	(*GetContactByIdResponse)(nil), // 3: contact.GetContactByIdResponse
	(*GetContactsRequest)(nil),     // 4: contact.GetContactsRequest
	(*GetContactsResponse)(nil),    // 5: contact.GetContactsResponse
	(*CreateContactRequest)(nil),   // 6: contact.CreateContactRequest
	(*CreateContactResponse)(nil),  // 7: contact.CreateContactResponse
	(*UpdateContactRequest)(nil),   // 8: contact.UpdateContactRequest
	(*UpdateContactResponse)(nil),  // 9: contact.UpdateContactResponse
	(*DeleteContactRequest)(nil),   // 10: contact.DeleteContactRequest
	(*DeleteContactResponse)(nil),  // 11: contact.DeleteContactResponse
	(*GetAddressByIdRequest)(nil),  // 12: contact.GetAddressByIdRequest
	(*GetAddressByIdResponse)(nil), // 13: contact.GetAddressByIdResponse
	(*GetAddressesRequest)(nil),    // 14: contact.GetAddressesRequest
	(*GetAddressesResponse)(nil),   // 15: contact.GetAddressesResponse
	(*CreateAddressRequest)(nil),   // 16: contact.CreateAddressRequest
	(*CreateAddressResponse)(nil),  // 17: contact.CreateAddressResponse
	(*UpdateAddressRequest)(nil),   // 18: contact.UpdateAddressRequest
	(*UpdateAddressResponse)(nil),  // 19: contact.UpdateAddressResponse
	(*DeleteAddressRequest)(nil),   // 20: contact.DeleteAddressRequest
	(*DeleteAddressResponse)(nil),  // 21: contact.DeleteAddressResponse
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
}
var file_proto_contact_contact_proto_depIdxs = []int32{
	22, // 0: contact.Contact.created_at:type_name -> google.protobuf.Timestamp
	22, // 1: contact.Address.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: contact.GetContactByIdResponse.contact:type_name -> contact.Contact
	0,  // 3: contact.GetContactsResponse.contacts:type_name -> contact.Contact
	0,  // 4: contact.CreateContactResponse.contact:type_name -> contact.Contact
	0,  // 5: contact.UpdateContactResponse.contact:type_name -> contact.Contact
	0,  // 6: contact.DeleteContactResponse.contact:type_name -> contact.Contact
	1,  // 7: contact.GetAddressByIdResponse.address:type_name -> contact.Address
	1,  // 8: contact.GetAddressesResponse.addresses:type_name -> contact.Address
	1,  // 9: contact.CreateAddressResponse.address:type_name -> contact.Address
	1,  // 10: contact.UpdateAddressResponse.address:type_name -> contact.Address
	1,  // 11: contact.DeleteAddressResponse.address:type_name -> contact.Address
	2,  // 12: contact.ContactService.GetContactById:input_type -> contact.GetContactByIdRequest
	4,  // 13: contact.ContactService.GetContacts:input_type -> contact.GetContactsRequest
	6,  // 14: contact.ContactService.CreateContact:input_type -> contact.CreateContactRequest
	8,  // 15: contact.ContactService.UpdateContact:input_type -> contact.UpdateContactRequest
	10, // 16: contact.ContactService.DeleteContact:input_type -> contact.DeleteContactRequest
	12, // 17: contact.ContactService.GetAddressById:input_type -> contact.GetAddressByIdRequest
	14, // 18: contact.ContactService.GetAddresses:input_type -> contact.GetAddressesRequest
	16, // 19: contact.ContactService.CreateAddress:input_type -> contact.CreateAddressRequest
	18, // 20: contact.ContactService.UpdateAddress:input_type -> contact.UpdateAddressRequest
	20, // 21: contact.ContactService.DeleteAddress:input_type -> contact.DeleteAddressRequest
	3,  // 22: contact.ContactService.GetContactById:output_type -> contact.GetContactByIdResponse
	5,  // 23: contact.ContactService.GetContacts:output_type -> contact.GetContactsResponse
	7,  // 24: contact.ContactService.CreateContact:output_type -> contact.CreateContactResponse
	9,  // 25: contact.ContactService.UpdateContact:output_type -> contact.UpdateContactResponse
	11, // 26: contact.ContactService.DeleteContact:output_type -> contact.DeleteContactResponse
	13, // 27: contact.ContactService.GetAddressById:output_type -> contact.GetAddressByIdResponse
	15, // 28: contact.ContactService.GetAddresses:output_type -> contact.GetAddressesResponse
	17, // 29: contact.ContactService.CreateAddress:output_type -> contact.CreateAddressResponse
	19, // 30: contact.ContactService.UpdateAddress:output_type -> contact.UpdateAddressResponse
	21, // 31: contact.ContactService.DeleteAddress:output_type -> contact.DeleteAddressResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_contact_contact_proto_init() }
func file_proto_contact_contact_proto_init() {
	if File_proto_contact_contact_proto != nil {
		return
	}
	file_proto_contact_contact_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_contact_contact_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_contact_contact_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_contact_contact_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_contact_contact_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_contact_contact_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_contact_contact_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_contact_contact_proto_rawDesc), len(file_proto_contact_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_contact_contact_proto_goTypes,
		DependencyIndexes: file_proto_contact_contact_proto_depIdxs,
		MessageInfos:      file_proto_contact_contact_proto_msgTypes,
	}.Build()
	File_proto_contact_contact_proto = out.File
	file_proto_contact_contact_proto_goTypes = nil
	file_proto_contact_contact_proto_depIdxs = nil
}
